"""Interfaces between the playback logic and the outside world.

GuildPlayer and PlayerRegistry only talk to these protocols. The real
implementations live in core.backend and core.lavalink_service; the soak test
and unit tests supply fakes. No Discord objects cross this boundary, only IDs.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from config import Config


class AudioPlayer(Protocol):
    """The subset of a Lavalink player that GuildPlayer drives."""

    paused: bool
    current: Any
    position: int

    async def play(self, track: Any, *, volume: int | None = None, pause: bool | None = None) -> None: ...

    async def stop(self) -> None: ...

    async def set_pause(self, pause: bool) -> None: ...

    async def set_volume(self, vol: int) -> None: ...

    async def seek(self, position: int) -> None: ...

    async def set_filter(self, _filter: Any, *, replace: bool = False) -> None: ...

    async def remove_filter(self, _filter: Any) -> None: ...

    async def clear_filters(self) -> None: ...


class PlayerBackend(Protocol):
    def audio(self, guild_id: int) -> AudioPlayer | None: ...

    def voice_connected(self, guild_id: int, channel_id: int | None) -> bool: ...

    def humans_in_channel(self, guild_id: int, channel_id: int) -> int | None: ...

    def any_node_available(self) -> bool: ...

    def guild_ids(self) -> set[int]: ...

    def stray_guild_ids(self) -> set[int]: ...

    async def connect(self, guild_id: int, channel_id: int) -> None: ...

    async def purge(self, guild_id: int) -> None: ...

    async def notify(self, channel_id: int, text: str) -> None: ...
    async def send_nowplaying_card(self, channel_id: int, container: Any, view: Any) -> int | None: ...
    async def edit_nowplaying_card(self, channel_id: int, message_id: int, container: Any, view: Any) -> bool: ...
    async def delete_nowplaying_card(self, channel_id: int, message_id: int) -> None: ...
    def bot_display_name(self, guild_id: int) -> str: ...
    def bot_avatar_url(self) -> str | None: ...
    def bot_id(self) -> int: ...


class TrackLoader(Protocol):
    async def load_first_with_source(self, guild_id: int, source: str, text: str) -> Any: ...
    async def load_with_source(self, guild_id: int, source: str, text: str) -> Any: ...



@dataclass(frozen=True)
class PlayerServices:
    cfg: Config
    backend: PlayerBackend
    loader: TrackLoader
    storage: Any | None = None
